apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: chat-apps
type: Opaque
stringData:
  MONGO_INIT_ROOT_USERNAME: root
  MONGO_INIT_ROOT_PASSWORD: admin
  MONGODB_URI: mongodb://root:admin@db-service:27017/chatApp?authSource=admin&retryWrites=true&w=majority
  NODE_ENV: production
  JWT_SECRET: fJYP0ZIsR5c1gho9jiyw7dIuOTJ1710AGRdXaFA3YfE
